format_version: 10
pipelines:
  mqs-gocd-staging:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      test-gocd:
        git: https://github.com/Mayank-032/Message_Queue_System
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - unit-testing:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-tests:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                - -v
                - ./...
                command: go
                run_if: passed
